before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: IdS9rQc5YVNhd970SnO9KA4Z3043LkjfUfNyPVHJfls7EdBGmpHzKNmZFsaWHi5ybjUkUPTEFyu299krm4hKynbQSdH6aCdH5+ZwBjn9LXDktvjOi9V4KXUub4GirQD/Szz1Abrbz77LeUG/8+RywWrlzFcf3WQiyCLeW49iEq+hrmLjZnb9wcWpmv8MwvAqguhEeZUOdYnjiy8j4znEksd4JsxaVLXqa4FXUVqiloMMCQN8jEttzxvrTTE8LcjjwBOODLC4SZh3Y10ChgsmXsXd7mxT8mELIpPRyapbkHj//8DbNhBMMixL6aBaw+8edItRnMNnGpPKV5VGmLWEhjLx/4ZhXSTLYPPV+6z8YzGBtI0VLQNNh90BZCmSpK+plMPJrqowN2E+Z45WxfnMjaEQtDSB37RFzlg1nYT8sQJNfcm7FJmah79T0oqoOiyQuGR5z0eNXI1KNdvDqJ1sqQEidt4zv3MWlz4oXi+vOSfhwYPd4kmZi3CyauAVvdHK+rOGQcmKoiSIrCHDOJy87GVuhpwDqxdMm5Oa2mjwgxmfcAYfEx8E3+xi8AgdDXkKGRTv+0NwcYFVMa8t01Jzf2oi+Nw8pSI45fcoxGcaruFM/+RCziHPUkyMkvMZYuOcMVZkchUolfRoou+zgsN6hXAsa6PcPtTJYEXQBC+I+NQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
